# Generated by Django 4.1.5 on 2023-01-09 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('insurance', '0004_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='claims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('national', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=255)),
                ('driver', models.CharField(max_length=255)),
                ('ownership', models.CharField(max_length=255)),
                ('authorized', models.CharField(max_length=255)),
                ('licenced', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('vehicle', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('reg', models.CharField(max_length=255)),
                ('address_where_it_occured', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('how_it_happened', models.CharField(max_length=255)),
                ('weather', models.CharField(max_length=255)),
                ('road_surface', models.CharField(max_length=255)),
                ('extent_of_damage', models.CharField(max_length=255)),
                ('estimate_repair_cost', models.CharField(max_length=255)),
                ('details_of_injuries', models.CharField(max_length=255)),
                ('passengers', models.CharField(max_length=255)),
                ('damaged_property', models.CharField(max_length=255)),
                ('names_of_third_parties', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Quotations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(max_length=255, upload_to='')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.claims')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PoliceReports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(max_length=255, upload_to='')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.claims')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(max_length=255, upload_to='')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.claims')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Damages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(max_length=255, upload_to='')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.claims')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
