# Generated by Django 4.1.5 on 2023-01-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_claims_quotations_policereports_licence_damages'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='Status',
            field=models.CharField(default='Pending', max_length=300),
        ),
    ]
