# Generated by Django 4.1.5 on 2023-01-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_claims_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='Remarks',
            field=models.CharField(default='Pending Assessment', max_length=500),
        ),
    ]
